### ISSUE TITLE
issues related to model2owl

### ISSUE THREAD

**Issue by VladimirAlexiev** [eprocurementontology/eprocurementontology#289]
I posted a number of issues in the "sibling project" that have an impact on this ontology. Here's a tracking list:

- [ ] https://github.com/OP-TED/model2owl/issues/91 domain/range correlations
- [ ] https://github.com/OP-TED/model2owl/issues/90 multiple inverses
- [ ] https://github.com/OP-TED/model2owl/issues/89 useless restrictions
- [ ] https://github.com/OP-TED/model2owl/issues/87 too many imports
- [ ] https://github.com/OP-TED/model2owl/issues/86 omit empty, `epos, epor` prefixes
- [ ] https://github.com/OP-TED/model2owl/issues/85 don't repeat term & ontology metadata in "shapes"
- [ ] https://github.com/OP-TED/model2owl/issues/84 why check for asymmetry? (`sh:sparql` is part of SPARQL Advanced)
- [ ] https://github.com/OP-TED/model2owl/issues/82 double domain and range
- [ ] https://github.com/OP-TED/model2owl/issues/81 useless singleton `unionOf`
- [ ] https://github.com/OP-TED/model2owl/issues/80 merge sh:property shapes
- [ ] https://github.com/OP-TED/model2owl/issues/78 predefined prefixes
- [ ] https://github.com/OP-TED/model2owl/issues/77 smarter CamelCase breaking

**Comment by VladimirAlexiev** [comment]
@eprocurementontology this is the ultimate `UML2OWL` issue, please give it that label
